"""add recipient_id and read_at to messages

Revision ID: 6b1101b11ca5
Revises: 0607c3fa3108
Create Date: 2025-09-09 09:27:22.874820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1101b11ca5'
# Now depends directly on results migration after chain linearization
down_revision = '20250908_02_results'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        try:
            batch_op.drop_column('recipient_id')
        except sa.exc.OperationalError:
            pass
        try:
            batch_op.drop_column('read_at')
        except sa.exc.OperationalError:
            pass

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_messages_recipient_id_users', 'users', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_recipient_id_users', type_='foreignkey')
        batch_op.drop_column('read_at')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###